version: '3.8'

services:
  frontend:
    image: ghcr.io/konopat/film-react-nest:sha-dcf28aadfbaeff203d4bf54461e0955b928777e6-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/konopat.nomorepartiessbs.ru:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ghcr.io/konopat/film-react-nest:sha-dcf28aadfbaeff203d4bf54461e0955b928777e6
    environment:
      - DATABASE_DRIVER=postgres
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=films
      - DATABASE_LOGGING=true
      - LOGGER_TYPE=json
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=films
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 